interpolation:
  enabled: true
  fps: 480
  speed: medium
  tuning: weak
  algorithm: 23
  gpu: true

frame blending:
  enabled: true
  output fps: 60
  intensity: 1.2
  weighting: gaussian | apex=2; std_dev=4; bound=(0, 2)

flowblur:
  enabled: false
  amount: 100
  mask:

encoding:
  process: ffmpeg
  args: x265 upscale

timescale:
  in: 1.0
  out: 1.0

output file:
  folder:
  container: .mp4
  prefix: 
  suffix: detailed

misc:
  mpv bin: mpv
  verbose: false
  dedup threshold: 0
